// Copyright (c) GiantCroissant. All rights reserved.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Plate.SCG.DI.ConstructorInjection;

[Generator(LanguageNames.CSharp)]
public sealed class SourceGenerator : IIncrementalGenerator
{
    private const string ConstructorInjection = "ConstructorInjection";
    private const string ConstructorInjectionAttribute = "ConstructorInjectionAttribute";
    private const string AttributeName = "ResolveInConstructor";
    private const string GenerateProperty = "GenerateProperty";
    private const string GeneratePropertyAttribute = "GeneratePropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, cancellationToken) =>
                    Utility.PredicateAsync(syntaxNode, ConstructorInjection, ConstructorInjectionAttribute, cancellationToken),
                Utility.TransformAsync)
            .Where(static typeSymbol => typeSymbol is not null)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, GenerateCode!);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<ITypeSymbol> typeSymbols)
    {
        if (typeSymbols.IsDefaultOrEmpty)
        {
            return;
        }

        var executingAssemblyName = Assembly.GetExecutingAssembly().GetName();
        foreach (var typeSymbol in typeSymbols)
        {
            var namespaceName = GetNamespaceName(typeSymbol);
            var fileName = string.IsNullOrWhiteSpace(namespaceName)
                ? $"{typeSymbol.Name}.DI.ConstructorInjection.g.cs"
                : $"{namespaceName}.{typeSymbol.Name}.DI.ConstructorInjection.g.cs";
            context.AddSource(fileName, GenerateCode(executingAssemblyName, fileName, typeSymbol));
        }
    }

    private static string GenerateCode(
        AssemblyName executingAssemblyName,
        string fileName,
        ITypeSymbol typeSymbol)
    {
        var assemblyName = $"{executingAssemblyName.Name}.{nameof(SourceGenerator)}";
        var assemblyVersion = $"{executingAssemblyName.Version}";
        var namespaceName = GetNamespaceName(typeSymbol);
        var typeDeclarationLine = Utility.CreateTypeDeclarationLine(typeSymbol);
        var typeName = typeSymbol.Name;
        var codeGenAttributes = Utility.CreateCodeGenAttributes(assemblyName, assemblyVersion);
        var attributedSymbols = GetResolveInConstructorSymbols(typeSymbol);
        var indentedAttributes = Utility.Indent(codeGenAttributes, 4);
        var parameters = CreateParams(attributedSymbols, 8);
        var assignment = CreateAssignment(attributedSymbols, 8);

        var builder = new System.Text.StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// {fileName}");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName};");
            builder.AppendLine();
        }
        builder.AppendLine(typeDeclarationLine);
        builder.AppendLine("{");
        builder.Append(indentedAttributes);
        builder.Append("    public ");
        builder.Append(typeName);
        builder.Append("(");
        builder.Append(parameters);
        builder.AppendLine(")");
        builder.AppendLine("    {");
        builder.AppendLine("        ConstructorBegin();");
        builder.AppendLine();
        if (!string.IsNullOrWhiteSpace(assignment))
        {
            builder.AppendLine(assignment);
            builder.AppendLine();
        }
        builder.AppendLine("        ConstructorEnd();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append(indentedAttributes);
        builder.AppendLine("    partial void ConstructorBegin();");
        builder.AppendLine();
        builder.Append(indentedAttributes);
        builder.AppendLine("    partial void ConstructorEnd();");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string GetNamespaceName(ITypeSymbol typeSymbol)
    {
        return typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
    }

    private static List<ISymbol> GetResolveInConstructorSymbols(ITypeSymbol typeSymbol)
    {
        var fromAttribute = Utility.GetAttributedSymbols(typeSymbol, AttributeName);
        var fromAutoProperties = GetAutoPropertyResolveFields(typeSymbol);

        return fromAttribute
            .Concat(fromAutoProperties)
            .Distinct<ISymbol>(SymbolEqualityComparer.Default)
            .ToList();
    }

    private static List<ISymbol> GetAutoPropertyResolveFields(ITypeSymbol typeSymbol)
    {
        var result = new List<ISymbol>();

        foreach (var field in typeSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            foreach (var attribute in field.GetAttributes())
            {
                var attributeName = attribute.AttributeClass?.Name;
                if (attributeName != GenerateProperty && attributeName != GeneratePropertyAttribute)
                {
                    continue;
                }

                var resolveArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == "ResolveInConstructor");
                if (resolveArg.Value.Value is bool resolve && resolve)
                {
                    result.Add(field);
                    break;
                }
            }
        }

        return result;
    }

    private static string CreateParams(List<ISymbol> symbols, int indent = 4)
    {
        var indentString = new string(' ', indent);
        var paramStrings = symbols
            .Select(symbol => (IFieldSymbol)symbol)
            .Select(fieldSymbol =>
            {
                var strippedUnderscore = fieldSymbol.Name.TrimStart('_');
                return $"{indentString}{fieldSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {strippedUnderscore},";
            })
            .ToList();

        const string newLine = "\n";
        var adjustedParamStrings = string
            .Join(newLine, paramStrings)
            .TrimEnd(',');

        if (string.IsNullOrWhiteSpace(adjustedParamStrings))
        {
            return string.Empty;
        }

        return newLine + adjustedParamStrings;
    }

    private static string CreateAssignment(List<ISymbol> symbols, int indent = 4)
    {
        var indentString = new string(' ', indent);
        var assignmentStrings = symbols
            .Select(symbol =>
            {
                var strippedUnderscore = symbol.Name.TrimStart('_');
                return $"{indentString}{symbol.Name} = {strippedUnderscore};";
            })
            .ToList();

        const string newLine = "\n";
        var adjustedAssignmentStrings = string
            .Join(newLine, assignmentStrings)
            .TrimStart(indentString.ToCharArray())
            .TrimEnd(newLine.ToCharArray().Concat(new[] { ',', ' ' }).ToArray());

        if (string.IsNullOrWhiteSpace(adjustedAssignmentStrings))
        {
            return string.Empty;
        }

        return adjustedAssignmentStrings;
    }
}
