// Copyright (c) GiantCroissant. All rights reserved.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Plate.SCG.General.DisposePattern;

[Generator(LanguageNames.CSharp)]
public sealed class SourceGenerator : IIncrementalGenerator
{
    private const string DisposePattern = "DisposePattern";
    private const string DisposePatternAttribute = "DisposePatternAttribute";
    private const string AttributeName = "ToBeDisposed";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, cancellationToken) =>
                    Utility.PredicateAsync(syntaxNode, DisposePattern, DisposePatternAttribute, cancellationToken),
                Utility.TransformAsync)
            .Where(static typeSymbol => typeSymbol is not null)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, GenerateCode!);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<ITypeSymbol> typeSymbols)
    {
        if (typeSymbols.IsDefaultOrEmpty)
        {
            return;
        }

        var executingAssemblyName = System.Reflection.Assembly.GetExecutingAssembly().GetName();
        foreach (var typeSymbol in typeSymbols)
        {
            var ns = typeSymbol.ContainingNamespace.ToDisplayString();
            var fileName = $"{ns}.{typeSymbol.Name}.General.DisposePattern.g.cs";
            context.AddSource(fileName, GenerateCode(executingAssemblyName, fileName, typeSymbol));
        }
    }

    private static string GenerateCode(
        AssemblyName executingAssemblyName,
        string fileName,
        ITypeSymbol typeSymbol)
    {
        var assemblyName = $"{executingAssemblyName.Name}.{nameof(SourceGenerator)}";
        var assemblyVersion = $"{executingAssemblyName.Version}";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var typeDeclarationLine = Utility.CreateTypeDeclarationLine(typeSymbol);
        var codeGenAttributes = Utility.CreateCodeGenAttributes(assemblyName, assemblyVersion);
        var indentedAttributes = Utility.Indent(codeGenAttributes, 4);
        var excludeFromCodeCoverageAttribute = Utility.CreateCodeGenAttributes(
            assemblyName,
            assemblyVersion,
            excludeFromCodeCoverage: false);
        var excludeIndentedAttributes = Utility.Indent(excludeFromCodeCoverageAttribute, 4);
        var createAsync = false;
        var disposeMethod = CreateDisposeMethod(
            assemblyName,
            assemblyVersion,
            typeSymbol,
            createAsync);

#pragma warning disable S2583 // Conditionally executed code should be reachable
        var asyncDisposedField = createAsync
            ? """
              {{excludeIndentedAttributes}}
                  private bool _asyncDisposed;
              """
            : string.Empty;
#pragma warning restore S2583 // Conditionally executed code should be reachable

        return
$$"""
// <auto-generated />

#nullable enable

namespace {{namespaceName}};

// ReSharper disable RedundantNameQualifier
[global::System.Diagnostics.CodeAnalysis.SuppressMessage(
    "Usage",
    "CA2213:DisposableFieldsShouldBeDisposed",
    Justification = "DisposePattern generator disposes all fields marked with [ToBeDisposed].")]
{{typeDeclarationLine}} :
    global::System.IDisposable
{
    {{asyncDisposedField}}
{{excludeIndentedAttributes}}
    private bool _disposed;

{{indentedAttributes}}
    public void Dispose()
    {
        Dispose(disposing: true);
        global::System.GC.SuppressFinalize(this);
    }
    {{disposeMethod}}
}
// ReSharper restore RedundantNameQualifier
""";
    }

    private static string CreateDisposeMethod(
        string assemblyName,
        string assemblyVersion,
        ITypeSymbol typeSymbol,
        bool createAsync = false,
        int indent = 4)
    {
        _ = indent;

        var codeGenAttributes = Utility.CreateCodeGenAttributes(assemblyName, assemblyVersion);
        var indentedAttributes = Utility.Indent(codeGenAttributes, 4);
        var disposeMethodArgs = createAsync
            ? "bool disposing, bool disposingAsync = false"
            : "bool disposing";
        var disposeAsyncStatement = createAsync
            ? """
              {{indentString}}if (disposingAsync)
              {{indentString}}{
              {{indentString}}    return;
              {{indentString}}}
              """
            : string.Empty;
        var disposeMethod = typeSymbol.IsSealed
            ? $"private void Dispose({disposeMethodArgs})"
            : $"protected virtual void Dispose({disposeMethodArgs})";

        var attributedSymbols = Utility.GetAttributedSymbols(typeSymbol, AttributeName);
        var cleanupStatements = CreateCleanupStatements(attributedSymbols, 12);

        return
$$"""

{{indentedAttributes}}
    {{disposeMethod}}
    {
        {{disposeAsyncStatement}}
        if (_disposed)
        {
            return;
        }

        if (disposing)
        {
            BeforeDisposeManagedResources();

            {{cleanupStatements}}

            DisposeManagedResources();
        }

        BeforeDisposeUnmanagedResources();

        DisposeUnmanagedResources();

        _disposed = true;
    }

{{indentedAttributes}}
    partial void BeforeDisposeManagedResources();

{{indentedAttributes}}
    partial void DisposeManagedResources();

{{indentedAttributes}}
    partial void BeforeDisposeUnmanagedResources();

{{indentedAttributes}}
    partial void DisposeUnmanagedResources();
""";
    }

    private static string CreateCleanupStatements(List<ISymbol> symbols, int indent = 4)
    {
        var indentString = new string(' ', indent);
#pragma warning disable S1135 // Track uses of "TODO" tags
        // TODO: Extract to examine more types
#pragma warning restore S1135 // Track uses of "TODO" tags
        var cleanupStrings = symbols
            .Select(symbol => (IFieldSymbol)symbol)
            .Select(fieldSymbol =>
            {
                var fieldName = fieldSymbol.Name;
                var fieldSymbolType = fieldSymbol.Type;
                var isReferenceType = fieldSymbolType.IsReferenceType;
                var readOnlyCleanup = fieldSymbol.IsReadOnly
                    ? "// Cannot reset readonly field"
                    : $"{fieldName} = null;";
                var assignToNull = isReferenceType
                    ? readOnlyCleanup
                    : "// Cannot reset readonly field";
                var implementsIDisposable = fieldSymbolType
                    .AllInterfaces
                    .Any(i => i.ToDisplayString().Equals("System.IDisposable", StringComparison.Ordinal));
                if (implementsIDisposable)
                {
                    if (!fieldSymbol.IsReadOnly && isReferenceType)
                    {
                        return
                            $$"""
                            {{indentString}}{
                            {{indentString}}    var toDispose = {{fieldName}};
                            {{indentString}}    {{fieldName}} = null;
                            {{indentString}}    if (toDispose is not null)
                            {{indentString}}    {
                            {{indentString}}        toDispose.Dispose();
                            {{indentString}}    }
                            {{indentString}}}
                            """;
                    }

                    return
                        $$"""
                        {{indentString}}if ({{fieldName}} is not null)
                        {{indentString}}{
                        {{indentString}}    {{fieldName}}.Dispose();
                        {{indentString}}    // Cannot reset readonly field
                        {{indentString}}}
                        """;
                }

                if (isReferenceType && !fieldSymbol.IsReadOnly)
                {
                    return
                        $$"""
                        {{indentString}}if ({{fieldName}} is not null)
                        {{indentString}}{
                        {{indentString}}    {{assignToNull}}
                        {{indentString}}}
                        """;
                }

                return string.Empty;
            })
            .ToList();

        var adjustedCleanupStrings = string
            .Join("\n", cleanupStrings)
            .TrimEnd(',');

        return
$$"""

{{adjustedCleanupStrings}}
""";
    }
}
