using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Plate.SCG.General.AutoProperties;

[Generator(LanguageNames.CSharp)]
public class SourceGenerator : IIncrementalGenerator
{
    private const string AutoProperty = "AutoProperty";
    private const string AutoPropertyAttribute = "AutoPropertyAttribute";
    private const string GenerateProperty = "GenerateProperty";
    private const string GeneratePropertyAttribute = "GeneratePropertyAttribute";
    private const string SkipProperty = "SkipProperty";
    private const string SkipPropertyAttribute = "SkipPropertyAttribute";

    private static readonly SymbolDisplayFormat FullyQualifiedWithNullable = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
                                 SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, cancellationToken) =>
                    Utility.PredicateAsync(syntaxNode, AutoProperty, AutoPropertyAttribute, cancellationToken),
                Utility.TransformAsync)
            .Where(static typeSymbol => typeSymbol is not null)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, GenerateCode!);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<ITypeSymbol> typeSymbols)
    {
        if (typeSymbols.IsDefaultOrEmpty)
        {
            return;
        }

        var executingAssemblyName = Assembly.GetExecutingAssembly().GetName();
        foreach (var typeSymbol in typeSymbols)
        {
            var ns = typeSymbol.ContainingNamespace.ToDisplayString();
            var fileName = $"{ns}.{typeSymbol.Name}.AutoProperties.g.cs";
            context.AddSource(fileName, GenerateCode(executingAssemblyName, fileName, typeSymbol));
        }
    }

    private static string GenerateCode(
        AssemblyName executingAssemblyName,
        string fileName,
        ITypeSymbol typeSymbol)
    {
        var assemblyName = $"{executingAssemblyName.Name}.{nameof(SourceGenerator)}";
        var assemblyVersion = $"{executingAssemblyName.Version}";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var typeDeclarationLine = Utility.CreateTypeDeclarationLine(typeSymbol);
        var codeGenAttributes = Utility.CreateCodeGenAttributes(assemblyName, assemblyVersion);
        var indentedAttributes = Utility.Indent(codeGenAttributes, 4);

        var autoPropertyConfig = GetAutoPropertyConfiguration(typeSymbol);
        var fieldsToGenerate = GetFieldsToGenerateProperties(typeSymbol, autoPropertyConfig);

        var properties = GenerateProperties(fieldsToGenerate, autoPropertyConfig);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// {fileName}");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine(typeDeclarationLine);
        sb.AppendLine("{");
        sb.Append(indentedAttributes);

        foreach (var property in properties)
        {
            sb.AppendLine(property);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static AutoPropertyConfiguration GetAutoPropertyConfiguration(ITypeSymbol typeSymbol)
    {
        var config = new AutoPropertyConfiguration();

        var autoPropertyAttribute = typeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == AutoProperty ||
                               a.AttributeClass?.Name == AutoPropertyAttribute);

        if (autoPropertyAttribute != null)
        {
            // Extract configuration from attribute arguments
            foreach (var namedArg in autoPropertyAttribute.NamedArguments)
            {
                switch (namedArg.Key)
                {
                    case nameof(config.DefaultAccessibility):
                        config.DefaultAccessibility = (PropertyAccessibility)(int)namedArg.Value.Value!;
                        break;
                    case nameof(config.DefaultPropertyKind):
                        config.DefaultPropertyKind = (PropertyKind)(int)namedArg.Value.Value!;
                        break;
                    case nameof(config.GenerateForAllFields):
                        config.GenerateForAllFields = (bool)namedArg.Value.Value!;
                        break;
                    case nameof(config.FieldPrefix):
                        config.FieldPrefix = (string)namedArg.Value.Value!;
                        break;
                }
            }
        }

        return config;
    }

    private static List<FieldPropertyInfo> GetFieldsToGenerateProperties(
        ITypeSymbol typeSymbol,
        AutoPropertyConfiguration config)
    {
        var privateFields = GetPrivateFields(typeSymbol);
        var fieldsToGenerate = new List<FieldPropertyInfo>();

        foreach (var field in privateFields)
        {
            var generatePropertyAttribute = field.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == GenerateProperty ||
                                   a.AttributeClass?.Name == GeneratePropertyAttribute);

            var skipPropertyAttribute = field.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == SkipProperty ||
                                   a.AttributeClass?.Name == SkipPropertyAttribute);

            // Skip if explicitly marked to skip
            if (skipPropertyAttribute != null)
                continue;

            // Generate if explicitly marked or if generating for all fields
            if (generatePropertyAttribute != null || config.GenerateForAllFields)
            {
                var fieldInfo = new FieldPropertyInfo
                {
                    Field = field,
                    PropertyName = GetPropertyName(field, generatePropertyAttribute, config),
                    Accessibility = GetPropertyAccessibility(generatePropertyAttribute, config),
                    PropertyKind = GetEffectivePropertyKind(field, generatePropertyAttribute, config),
                    IsRequired = GetIsRequired(generatePropertyAttribute)
                };

                fieldsToGenerate.Add(fieldInfo);
            }
        }

        return fieldsToGenerate;
    }

    private static string GetPropertyName(
        IFieldSymbol field,
        AttributeData? generatePropertyAttribute,
        AutoPropertyConfiguration config)
    {
        // Check if property name is explicitly specified
        if (generatePropertyAttribute != null)
        {
            var propertyNameArg = generatePropertyAttribute.NamedArguments
                .FirstOrDefault(arg => arg.Key == "PropertyName");

            if (propertyNameArg.Value.Value is string explicitName && !string.IsNullOrWhiteSpace(explicitName))
            {
                return explicitName;
            }
        }

        // Generate from field name
        return FieldNameToPropertyName(field.Name, config.FieldPrefix);
    }

    private static PropertyAccessibility GetPropertyAccessibility(
        AttributeData? generatePropertyAttribute,
        AutoPropertyConfiguration config)
    {
        if (generatePropertyAttribute != null)
        {
            var accessibilityArg = generatePropertyAttribute.NamedArguments
                .FirstOrDefault(arg => arg.Key == "Accessibility");

            if (accessibilityArg.Value.Value != null)
            {
                return (PropertyAccessibility)(int)accessibilityArg.Value.Value;
            }
        }

        return config.DefaultAccessibility;
    }

    private static PropertyKind GetPropertyKind(
        AttributeData? generatePropertyAttribute,
        AutoPropertyConfiguration config)
    {
        if (generatePropertyAttribute != null)
        {
            var propertyKindArg = generatePropertyAttribute.NamedArguments
                .FirstOrDefault(arg => arg.Key == "PropertyKind");

            if (propertyKindArg.Value.Value != null)
            {
                return (PropertyKind)(int)propertyKindArg.Value.Value;
            }
        }

        return config.DefaultPropertyKind;
    }

    private static PropertyKind GetEffectivePropertyKind(
        IFieldSymbol field,
        AttributeData? generatePropertyAttribute,
        AutoPropertyConfiguration config)
    {
        var requestedKind = GetPropertyKind(generatePropertyAttribute, config);

        // For readonly fields, we cannot legally generate setters or init accessors that assign to the field.
        // To preserve immutability and avoid compile errors, always treat readonly fields as GetterOnly.
        if (field.IsReadOnly)
        {
            return PropertyKind.GetterOnly;
        }

        return requestedKind;
    }

    private static bool GetIsRequired(AttributeData? generatePropertyAttribute)
    {
        if (generatePropertyAttribute != null)
        {
            var isRequiredArg = generatePropertyAttribute.NamedArguments
                .FirstOrDefault(arg => arg.Key == "IsRequired");

            if (isRequiredArg.Value.Value is bool isRequired)
            {
                return isRequired;
            }
        }

        return false;
    }

    private static List<string> GenerateProperties(
        List<FieldPropertyInfo> fieldsToGenerate,
        AutoPropertyConfiguration config)
    {
        var properties = new List<string>();

        foreach (var fieldInfo in fieldsToGenerate)
        {
            var property = GeneratePropertyCode(fieldInfo);
            properties.Add(property);
        }

        return properties;
    }

    private static string GeneratePropertyCode(FieldPropertyInfo fieldInfo)
    {
        var accessibilityModifier = GetAccessibilityModifier(fieldInfo.Accessibility);
        var fieldName = fieldInfo.Field.Name;
        var propertyName = fieldInfo.PropertyName;

        // Preserve nullable annotations (e.g., string? / IReadOnlyList<T>?) so the generated
        // property signature matches the backing field and avoids nullable analysis warnings.
        var fieldTypeSymbol = fieldInfo.Field.Type.WithNullableAnnotation(fieldInfo.Field.NullableAnnotation);
        var fieldType = fieldTypeSymbol.ToDisplayString(FullyQualifiedWithNullable);
        var requiredModifier = fieldInfo.IsRequired ? "required " : string.Empty;
        var propertyType = requiredModifier + fieldType;

        var getterExpression = GetGetterExpression(fieldInfo.Field, fieldName);

        var propertyCode = fieldInfo.PropertyKind switch
        {
            PropertyKind.GetterOnly => GenerateGetterOnlyProperty(accessibilityModifier, propertyType, propertyName, getterExpression),
            PropertyKind.GetterPrivateSetter => GenerateGetterPrivateSetterProperty(accessibilityModifier, propertyType, propertyName, getterExpression, fieldName),
            PropertyKind.GetterProtectedSetter => GenerateGetterProtectedSetterProperty(accessibilityModifier, propertyType, propertyName, getterExpression, fieldName),
            PropertyKind.GetterInternalSetter => GenerateGetterInternalSetterProperty(accessibilityModifier, propertyType, propertyName, getterExpression, fieldName),
            PropertyKind.GetterInitOnly => GenerateGetterInitOnlyProperty(accessibilityModifier, propertyType, propertyName, getterExpression, fieldName),
            _ => GenerateGetterSetterProperty(accessibilityModifier, propertyType, propertyName, getterExpression, fieldName)
        };

        return Utility.Indent(propertyCode, 4);
    }

    private static string GetAccessibilityModifier(PropertyAccessibility accessibility)
    {
        return accessibility switch
        {
            PropertyAccessibility.Public => "public",
            PropertyAccessibility.Internal => "internal",
            PropertyAccessibility.Protected => "protected",
            PropertyAccessibility.Private => "private",
            _ => "public"
        };
    }

    private static string GenerateGetterSetterProperty(string accessibility, string type, string propertyName, string getterExpression, string fieldName)
    {
        return $@"{accessibility} {type} {propertyName}
{{
    get => {getterExpression};
    set => {fieldName} = value;
}}";
    }

    private static string GenerateGetterOnlyProperty(string accessibility, string type, string propertyName, string getterExpression)
    {
        return $@"{accessibility} {type} {propertyName}
{{
    get => {getterExpression};
}}";
    }

    private static string GenerateGetterPrivateSetterProperty(string accessibility, string type, string propertyName, string getterExpression, string fieldName)
    {
        return $@"{accessibility} {type} {propertyName}
{{
    get => {getterExpression};
    private set => {fieldName} = value;
}}";
    }

    private static string GenerateGetterProtectedSetterProperty(string accessibility, string type, string propertyName, string getterExpression, string fieldName)
    {
        return $@"{accessibility} {type} {propertyName}
{{
    get => {getterExpression};
    protected set => {fieldName} = value;
}}";
    }

    private static string GenerateGetterInternalSetterProperty(string accessibility, string type, string propertyName, string getterExpression, string fieldName)
    {
        return $@"{accessibility} {type} {propertyName}
{{
    get => {getterExpression};
    internal set => {fieldName} = value;
}}";
    }

    private static string GenerateGetterInitOnlyProperty(string accessibility, string type, string propertyName, string getterExpression, string fieldName)
    {
        return $@"{accessibility} {type} {propertyName}
{{
    get => {getterExpression};
    init => {fieldName} = value;
}}";
    }

    private static string GetGetterExpression(IFieldSymbol field, string fieldName)
    {
        // If a field is a non-nullable reference type but not definitely assigned,
        // returning it from a generated getter triggers CS8603 under #nullable enable.
        // Using the null-forgiving operator keeps the generated API surface intact
        // while avoiding pervasive warnings in consuming (non-test) projects.
        var fieldType = field.Type;

        if (fieldType.IsReferenceType && field.NullableAnnotation != NullableAnnotation.Annotated)
        {
            return fieldName + "!";
        }

        return fieldName;
    }

    private class AutoPropertyConfiguration
    {
        public PropertyAccessibility DefaultAccessibility { get; set; } = PropertyAccessibility.Public;
        public PropertyKind DefaultPropertyKind { get; set; } = PropertyKind.GetterSetter;
        public bool GenerateForAllFields { get; set; } = false;
        public string FieldPrefix { get; set; } = "_";
    }

    private class FieldPropertyInfo
    {
        public IFieldSymbol Field { get; set; } = null!;
        public string PropertyName { get; set; } = string.Empty;
        public PropertyAccessibility Accessibility { get; set; }
        public PropertyKind PropertyKind { get; set; }
        public bool IsRequired { get; set; }
    }

    // These enums mirror the ones in the attributes package
    private enum PropertyAccessibility
    {
        Public,
        Internal,
        Protected,
        Private
    }

    private enum PropertyKind
    {
        GetterSetter,
        GetterOnly,
        GetterPrivateSetter,
        GetterProtectedSetter,
        GetterInternalSetter,
        GetterInitOnly
    }

    // Helper methods for field processing
    private static List<IFieldSymbol> GetPrivateFields(ITypeSymbol typeSymbol)
    {
        return typeSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.DeclaredAccessibility == Accessibility.Private)
            .Where(f => !f.IsStatic)
            .Where(f => !f.IsConst)
            .ToList();
    }

    private static string FieldNameToPropertyName(string fieldName, string fieldPrefix = "_")
    {
        if (string.IsNullOrEmpty(fieldName))
            return fieldName;

        var propertyName = fieldName;

        // Remove prefix if it exists
        if (!string.IsNullOrEmpty(fieldPrefix) && propertyName.StartsWith(fieldPrefix))
        {
            propertyName = propertyName.Substring(fieldPrefix.Length);
        }

        // Convert to Pascal case
        if (propertyName.Length > 0)
        {
            propertyName = char.ToUpperInvariant(propertyName[0]) + propertyName.Substring(1);
        }

        return propertyName;
    }
}
