using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Plate.SCG.Resilience.Decorator;

[Generator(LanguageNames.CSharp)]
public sealed class SourceGenerator : IIncrementalGenerator
{
    private sealed class NamedTypeComparer : IEqualityComparer<INamedTypeSymbol>
    {
        public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y)
            => SymbolEqualityComparer.Default.Equals(x, y);

        public int GetHashCode(INamedTypeSymbol obj)
            => SymbolEqualityComparer.Default.GetHashCode(obj);
    }

    private static readonly SymbolDisplayFormat FullyQualified = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                              SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaceSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, cancellationToken) => Utility.Predicate(syntaxNode, cancellationToken),
                static (ctx, cancellationToken) => Utility.Transform(ctx, cancellationToken))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        context.RegisterSourceOutput(interfaceSymbols, GenerateCode);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol> interfaceSymbols)
    {
        if (interfaceSymbols.IsDefaultOrEmpty)
        {
            return;
        }

        var executingAssemblyName = Assembly.GetExecutingAssembly().GetName();

        foreach (var iface in interfaceSymbols.Distinct(new NamedTypeComparer()))
        {
            var ns = iface.ContainingNamespace?.ToDisplayString() ?? string.Empty;
            var decoratorName = GetDecoratorName(iface);
            var fileName = string.IsNullOrWhiteSpace(ns)
                ? $"{decoratorName}.Resilience.Decorator.g.cs"
                : $"{ns}.{decoratorName}.Resilience.Decorator.g.cs";

            var source = GenerateDecoratorSource(executingAssemblyName, fileName, iface, decoratorName);
            context.AddSource(fileName, source);
        }
    }

    private static string GetDecoratorName(INamedTypeSymbol iface)
    {
        return iface.Name + "ResilienceDecorator";
    }

    private static string GenerateDecoratorSource(
        AssemblyName executingAssemblyName,
        string fileName,
        INamedTypeSymbol iface,
        string decoratorName)
    {
        var assemblyName = $"{executingAssemblyName.Name}.{nameof(SourceGenerator)}";
        var assemblyVersion = $"{executingAssemblyName.Version}";

        var ns = iface.ContainingNamespace?.ToDisplayString() ?? string.Empty;
        var accessibility = iface.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";

        var ifaceType = iface.ToDisplayString(FullyQualified);
        var typeParamsDecl = GetTypeParametersDeclaration(iface);
        var typeConstraints = GetTypeConstraints(iface);

        var interfacePolicyName = GetPolicyNameFromAttributes(iface.GetAttributes());
        if (string.IsNullOrWhiteSpace(interfacePolicyName))
        {
            interfacePolicyName = iface.ToDisplayString();
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// {fileName}");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"[{CreateGeneratedCodeAttribute(assemblyName, assemblyVersion)}]");
        sb.AppendLine($"[{CreateDebuggerNonUserCodeAttribute()}]");
        sb.Append($"{accessibility} sealed class {decoratorName}{typeParamsDecl} : {ifaceType}");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(typeConstraints))
        {
            sb.Append(typeConstraints);
        }

        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {ifaceType} _inner;");
        sb.AppendLine("    private readonly global::Plate.Resilience.IResilienceService _resilience;");
        sb.AppendLine("    private readonly global::Plate.Resilience.IResiliencePolicyProvider _policyProvider;");
        sb.AppendLine();
        sb.AppendLine($"    public {decoratorName}(");
        sb.AppendLine($"        {ifaceType} inner,");
        sb.AppendLine("        global::Plate.Resilience.IResilienceService resilience,");
        sb.AppendLine("        global::Plate.Resilience.IResiliencePolicyProvider policyProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner ?? throw new global::System.ArgumentNullException(nameof(inner));");
        sb.AppendLine("        _resilience = resilience ?? throw new global::System.ArgumentNullException(nameof(resilience));");
        sb.AppendLine("        _policyProvider = policyProvider ?? throw new global::System.ArgumentNullException(nameof(policyProvider));");
        sb.AppendLine("    }");

        foreach (var member in iface.GetMembers())
        {
            switch (member)
            {
                case IPropertySymbol prop:
                    GenerateProperty(sb, prop);
                    break;
                case IEventSymbol evt:
                    GenerateEvent(sb, evt);
                    break;
                case IMethodSymbol method:
                    if (method.MethodKind == MethodKind.Ordinary)
                    {
                        GenerateMethod(sb, method, interfacePolicyName);
                    }
                    break;
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string CreateGeneratedCodeAttribute(string assemblyName, string assemblyVersion)
        => $"global::System.CodeDom.Compiler.GeneratedCode(\"{assemblyName}\", \"{assemblyVersion}\")";

    private static string CreateDebuggerNonUserCodeAttribute()
        => "global::System.Diagnostics.DebuggerNonUserCode";

    private static void GenerateProperty(StringBuilder sb, IPropertySymbol prop)
    {
        var propType = prop.Type.ToDisplayString(FullyQualified);
        sb.AppendLine();
        sb.AppendLine($"    public {propType} {prop.Name}");
        sb.AppendLine("    {");

        if (prop.GetMethod is not null)
        {
            sb.AppendLine($"        get => _inner.{prop.Name};");
        }

        if (prop.SetMethod is not null)
        {
            sb.AppendLine($"        set => _inner.{prop.Name} = value;");
        }

        sb.AppendLine("    }");
    }

    private static void GenerateEvent(StringBuilder sb, IEventSymbol evt)
    {
        var evtType = evt.Type.ToDisplayString(FullyQualified);
        sb.AppendLine();
        sb.AppendLine($"    public event {evtType} {evt.Name}");
        sb.AppendLine("    {");
        sb.AppendLine($"        add => _inner.{evt.Name} += value;");
        sb.AppendLine($"        remove => _inner.{evt.Name} -= value;");
        sb.AppendLine("    }");
    }

    private static void GenerateMethod(
        StringBuilder sb,
        IMethodSymbol method,
        string interfacePolicyName)
    {
        sb.AppendLine();

        sb.Append("    public ");
        sb.Append(IsVoid(method.ReturnType)
            ? "void"
            : method.ReturnType.ToDisplayString(FullyQualified));
        sb.Append(" ");
        sb.Append(method.Name);

        if (method.IsGenericMethod)
        {
            sb.Append("<");
            for (var i = 0; i < method.TypeParameters.Length; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                sb.Append(method.TypeParameters[i].Name);
            }
            sb.Append(">");
        }

        sb.Append("(");
        for (var i = 0; i < method.Parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            var p = method.Parameters[i];
            if (p.IsParams)
            {
                sb.Append("params ");
            }

            sb.Append(p.Type.ToDisplayString(FullyQualified));
            sb.Append(" ");
            sb.Append(p.Name);
        }
        sb.Append(")");
        sb.AppendLine();

        AppendMethodConstraints(sb, method);

        sb.AppendLine("    {");

        var policyName = GetPolicyNameFromAttributes(method.GetAttributes());
        if (string.IsNullOrWhiteSpace(policyName))
        {
            policyName = interfacePolicyName;
        }

        var ctParam = method.Parameters.FirstOrDefault(p =>
            p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.CancellationToken");

        var ctExpr = ctParam is null ? "default" : ctParam.Name;

        var innerCallArgs = new List<string>();
        var innerCallArgsWithToken = new List<string>();
        foreach (var p in method.Parameters)
        {
            if (ctParam is not null && SymbolEqualityComparer.Default.Equals(p, ctParam))
            {
                innerCallArgs.Add(p.Name);
                innerCallArgsWithToken.Add("token");
                continue;
            }

            innerCallArgs.Add(p.Name);
            innerCallArgsWithToken.Add(p.Name);
        }

        var innerCall = $"_inner.{method.Name}{GetMethodTypeArgumentsUsage(method)}({string.Join(", ", innerCallArgs)})";
        var innerCallWithToken = $"_inner.{method.Name}{GetMethodTypeArgumentsUsage(method)}({string.Join(", ", innerCallArgsWithToken)})";

        if (IsVoid(method.ReturnType) || method.Parameters.Any(p => p.RefKind != RefKind.None))
        {
            // Can't safely wrap ref/out/in methods into the resilience lambda.
            // Also handle void return types.
            if (IsVoid(method.ReturnType))
            {
                sb.AppendLine($"        {innerCall};");
            }
            else
            {
                sb.AppendLine($"        return {innerCall};");
            }
        }
        else if (IsTask(method.ReturnType) || IsTaskOfT(method.ReturnType))
        {
            sb.AppendLine($"        return global::Plate.Resilience.ResilienceServiceExtensions.ExecuteAsync(_resilience, _policyProvider, \"{EscapeStringLiteral(policyName)}\", token => {innerCallWithToken}, {ctExpr});");
        }
        else
        {
            sb.AppendLine($"        return {innerCall};");
        }

        sb.AppendLine("    }");
    }

    private static string EscapeStringLiteral(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static bool IsTask(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named)
        {
            return false;
        }

        return named.Name == "Task" &&
               named.TypeArguments.Length == 0 &&
               named.ContainingNamespace?.ToDisplayString() == "System.Threading.Tasks";
    }

    private static bool IsTaskOfT(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named)
        {
            return false;
        }

        return named.Name == "Task" &&
               named.TypeArguments.Length == 1 &&
               named.ContainingNamespace?.ToDisplayString() == "System.Threading.Tasks";
    }

    private static bool IsVoid(ITypeSymbol type)
    {
        return type.SpecialType == SpecialType.System_Void;
    }

    private static void AppendMethodConstraints(StringBuilder sb, IMethodSymbol method)
    {
        if (!method.IsGenericMethod)
        {
            return;
        }

        foreach (var typeParam in method.TypeParameters)
        {
            var constraints = new List<string>();

            if (typeParam.HasReferenceTypeConstraint)
            {
                constraints.Add("class");
            }

            if (typeParam.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }

            if (typeParam.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            if (typeParam.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            foreach (var ct in typeParam.ConstraintTypes)
            {
                constraints.Add(ct.ToDisplayString(FullyQualified));
            }

            if (constraints.Count > 0)
            {
                sb.AppendLine($"        where {typeParam.Name} : {string.Join(", ", constraints)}");
            }
        }
    }

    private static string? GetPolicyNameFromAttributes(ImmutableArray<AttributeData> attributes)
    {
        foreach (var attribute in attributes)
        {
            var name = attribute.AttributeClass?.Name;
            if (name != "ResilientAttribute" && name != "Resilient")
            {
                continue;
            }

            if (attribute.ConstructorArguments.Length == 1 &&
                attribute.ConstructorArguments[0].Value is string s &&
                !string.IsNullOrWhiteSpace(s))
            {
                return s;
            }

            return null;
        }

        return null;
    }

    private static string GetTypeParametersDeclaration(INamedTypeSymbol type)
    {
        if (type.TypeParameters.Length == 0)
        {
            return string.Empty;
        }

        return "<" + string.Join(", ", type.TypeParameters.Select(t => t.Name)) + ">";
    }


    private static string GetTypeConstraints(INamedTypeSymbol type)
    {
        if (type.TypeParameters.Length == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var typeParam in type.TypeParameters)
        {
            var constraints = new List<string>();

            if (typeParam.HasReferenceTypeConstraint)
            {
                constraints.Add("class");
            }

            if (typeParam.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }

            if (typeParam.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            if (typeParam.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            foreach (var ct in typeParam.ConstraintTypes)
            {
                constraints.Add(ct.ToDisplayString(FullyQualified));
            }

            if (constraints.Count > 0)
            {
                sb.AppendLine($"    where {typeParam.Name} : {string.Join(", ", constraints)}");
            }
        }

        return sb.ToString();
    }

    private static string GetMethodTypeArgumentsUsage(IMethodSymbol method)
    {
        if (!method.IsGenericMethod)
        {
            return string.Empty;
        }

        return "<" + string.Join(", ", method.TypeParameters.Select(t => t.Name)) + ">";
    }
}
