using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Plate.SCG.General.AutoToString;

[Generator(LanguageNames.CSharp)]
public class SourceGenerator : IIncrementalGenerator
{
    private const string AutoToString = "AutoToString";
    private const string AutoToStringAttribute = "AutoToStringAttribute";
    private const string AddToString = "AddToString";
    private const string AddToStringAttribute = "AddToStringAttribute";
    private const string GenerateProperty = "GenerateProperty";
    private const string GeneratePropertyAttribute = "GeneratePropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, cancellationToken) =>
                    Utility.PredicateAsync(syntaxNode, AutoToString, AutoToStringAttribute, cancellationToken),
                Utility.TransformAsync)
            .Where(static typeSymbol => typeSymbol is not null)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, GenerateCode!);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<ITypeSymbol> typeSymbols)
    {
        if (typeSymbols.IsDefaultOrEmpty)
        {
            return;
        }

        var executingAssemblyName = Assembly.GetExecutingAssembly().GetName();
        foreach (var typeSymbol in typeSymbols)
        {
            var ns = typeSymbol.ContainingNamespace.ToDisplayString();
            var fileName = $"{ns}.{typeSymbol.Name}.General.AutoToString.g.cs";
            context.AddSource(fileName, GenerateCode(executingAssemblyName, fileName, typeSymbol));
        }
    }

    private static string GenerateCode(
        AssemblyName executingAssemblyName,
        string fileName,
        ITypeSymbol typeSymbol)
    {
        var assemblyName = $"{executingAssemblyName.Name}.{nameof(SourceGenerator)}";
        var assemblyVersion = $"{executingAssemblyName.Version}";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var typeDeclarationLine = Utility.CreateTypeDeclarationLine(typeSymbol);
        var codeGenAttributes = Utility.CreateCodeGenAttributes(assemblyName, assemblyVersion);
        var indentedAttributes = Utility.Indent(codeGenAttributes, 4);

        var toStringSymbols = GetToStringSymbols(typeSymbol);
        var desc = CreateString(toStringSymbols, typeSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// {fileName}");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine(typeDeclarationLine);
        sb.AppendLine("{");
        sb.Append(indentedAttributes);
        sb.AppendLine("    public override string ToString()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return $$\"\"\"{CreateReturnStatement(typeSymbol, desc)}\"\"\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string CreateReturnStatement(
        ITypeSymbol typeSymbol,
        string desc)
    {
        return $"{typeSymbol.Name} {desc}";
    }

    private static List<ISymbol> GetToStringSymbols(ITypeSymbol typeSymbol)
    {
        var fromAddToString = Utility.GetAttributedSymbols(typeSymbol, AddToString);
        var fromAutoProperties = GetAutoPropertyToStringFields(typeSymbol);

        return fromAddToString
            .Concat(fromAutoProperties)
            .Distinct<ISymbol>(SymbolEqualityComparer.Default)
            .ToList();
    }

    private static List<ISymbol> GetAutoPropertyToStringFields(ITypeSymbol typeSymbol)
    {
        var result = new List<ISymbol>();

        foreach (var field in typeSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            foreach (var attribute in field.GetAttributes())
            {
                var attributeName = attribute.AttributeClass?.Name;
                if (attributeName != GenerateProperty && attributeName != GeneratePropertyAttribute)
                {
                    continue;
                }

                var includeArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == "IncludeInToString");
                if (includeArg.Value.Value is bool include && include)
                {
                    result.Add(field);
                    break;
                }
            }
        }

        return result;
    }

    private static string CreateString(
        List<ISymbol> addToStrings,
        ITypeSymbol typeSymbol)
    {
        var contentBuilder = new StringBuilder();
        var isFirst = true;
        foreach (var addToString in addToStrings)
        {
            var symbolType = addToString switch
            {
                IPropertySymbol p => p.Type,
                IFieldSymbol f => f.Type,
                _ => null
            };

            var accessorName = addToString.Name;
            var displayName = accessorName;

            if (addToString is IFieldSymbol field &&
                TryGetAutoPropertyDisplayName(field, typeSymbol, out var autoPropDisplayName))
            {
                displayName = autoPropDisplayName;
            }

            if (!isFirst)
            {
                contentBuilder.Append(", ");
            }

            var isNullable = symbolType?.NullableAnnotation == NullableAnnotation.Annotated || symbolType?.IsReferenceType == true;

            if (symbolType != null && IsDictionary(symbolType))
            {
                contentBuilder.Append(displayName);
                contentBuilder.Append(" = {{");
                contentBuilder.Append(accessorName);
                contentBuilder.Append(" != null ? \"[\" + string.Join(\", \", global::System.Linq.Enumerable.Select(");
                contentBuilder.Append(accessorName);
                contentBuilder.Append(", kvp => kvp.Key + \"=\" + kvp.Value)) + \"]\" : \"null\"}}");
            }
            else if (symbolType != null && IsCollection(symbolType))
            {
                contentBuilder.Append(displayName);
                contentBuilder.Append(" = {{");
                contentBuilder.Append(accessorName);
                contentBuilder.Append(" != null ? \"[\" + string.Join(\", \", ");
                contentBuilder.Append(accessorName);
                contentBuilder.Append(") + \"]\" : \"null\"}}");
            }
            else if (isNullable && symbolType?.SpecialType != SpecialType.System_String)
            {
                contentBuilder.Append(displayName);
                contentBuilder.Append(" = {{");
                contentBuilder.Append(accessorName);
                contentBuilder.Append(" != null ? ");
                contentBuilder.Append(accessorName);
                contentBuilder.Append(".ToString() : \"null\"}}");
            }
            else
            {
                contentBuilder.Append(displayName);
                contentBuilder.Append(" = {{");
                contentBuilder.Append(accessorName);
                contentBuilder.Append("}}");
            }

            isFirst = false;
        }

        var interpolated = contentBuilder.ToString();
        return interpolated;
    }

    private static bool TryGetAutoPropertyDisplayName(
        IFieldSymbol field,
        ITypeSymbol containingType,
        out string displayName)
    {
        displayName = string.Empty;

        foreach (var attribute in field.GetAttributes())
        {
            var attributeName = attribute.AttributeClass?.Name;
            if (attributeName != GenerateProperty && attributeName != GeneratePropertyAttribute)
            {
                continue;
            }

            var includeArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == "IncludeInToString");
            if (includeArg.Value.Value is bool include && include)
            {
                var fieldPrefix = GetFieldPrefix(containingType);
                displayName = FieldNameToPropertyName(field.Name, fieldPrefix);
                return true;
            }
        }

        return false;
    }

    private static string GetFieldPrefix(ITypeSymbol typeSymbol)
    {
        const string defaultPrefix = "_";

        var autoPropertyAttribute = typeSymbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.Name == "AutoProperty" ||
                a.AttributeClass?.Name == "AutoPropertyAttribute");

        if (autoPropertyAttribute != null)
        {
            var fieldPrefixArg = autoPropertyAttribute.NamedArguments
                .FirstOrDefault(a => a.Key == "FieldPrefix");

            if (fieldPrefixArg.Value.Value is string prefix &&
                !string.IsNullOrEmpty(prefix))
            {
                return prefix;
            }
        }

        return defaultPrefix;
    }

    private static string FieldNameToPropertyName(string fieldName, string fieldPrefix)
    {
        if (string.IsNullOrEmpty(fieldName))
        {
            return fieldName;
        }

        var propertyName = fieldName;

        if (!string.IsNullOrEmpty(fieldPrefix) &&
            propertyName.StartsWith(fieldPrefix, StringComparison.Ordinal))
        {
            propertyName = propertyName.Substring(fieldPrefix.Length);
        }

        if (propertyName.Length > 0)
        {
            propertyName = char.ToUpperInvariant(propertyName[0]) + propertyName.Substring(1);
        }

        return propertyName;
    }

    private static bool IsDictionary(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        foreach (var @interface in namedType.AllInterfaces)
        {
            var originalDefinition = @interface.OriginalDefinition?.ToDisplayString() ?? string.Empty;

            if (originalDefinition.Equals("System.Collections.Generic.IDictionary<TKey, TValue>", StringComparison.Ordinal) ||
                originalDefinition.Equals("System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsCollection(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol)
        {
            return true;
        }

        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        if (type.SpecialType == SpecialType.System_String)
        {
            return false;
        }

        foreach (var @interface in namedType.AllInterfaces)
        {
            var originalDefinition = @interface.OriginalDefinition?.ToDisplayString() ?? string.Empty;

            if (originalDefinition.Equals("System.Collections.IEnumerable", StringComparison.Ordinal) ||
                originalDefinition.Equals("System.Collections.Generic.IEnumerable<T>", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }
}
