<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Plate.SCG.General.DisposePattern.Attributes</AssemblyName>
    <RootNamespace>Plate.SCG.General.DisposePattern.Attributes</RootNamespace>
    <PackageId>GiantCroissant.Plate.SCG.General.DisposePattern.Attributes</PackageId>
    <Version>$(GITVERSION_MAJORMINORPATCH)</Version>
    <Authors>Lunar Horse</Authors>
    <Description>Attributes for Plate.SCG.General.DisposePattern source generator.</Description>
    <PackageTags>source-generator;roslyn;dispose-pattern;attributes</PackageTags>
    <DevelopmentDependency>false</DevelopmentDependency>
    <IncludeBuildOutput>true</IncludeBuildOutput>
  </PropertyGroup>

</Project>
